/*! ******************************************************************************
 *
 * Pentaho
 *
 * Copyright (C) 2024 by Hitachi Vantara, LLC : http://www.pentaho.com
 *
 * Use of this software is governed by the Business Source License included
 * in the LICENSE.TXT file.
 *
 * Change Date: 2028-08-13
 ******************************************************************************/

package org.pentaho.reporting.libraries.fonts.encoding;

import java.io.Serializable;

/**
 * Serialized instances of this class are generated by the EncodingGenerator and stored as serialized classes. This is
 * more space conserving than creating a separate class for each encoding.
 *
 * @author Thomas Morgner
 */
public abstract class EncodingData implements Serializable {
  private static final long serialVersionUID = 8474288154717664509L;

  protected EncodingData() {
  }
}
