#
# Copyright (c) 2007 - 2026, Pentaho. All Rights Reserved.
#
display-name=UPPER
description=Converts text to uppercase.
parameter.0.display-name=text
parameter.0.description=The text in which lower case letters are to be converted to capitals.
