/*! ******************************************************************************
 *
 * Pentaho
 *
 * Copyright (C) 2024 by Hitachi Vantara, LLC : http://www.pentaho.com
 *
 * Use of this software is governed by the Business Source License included
 * in the LICENSE.TXT file.
 *
 * Change Date: 2028-08-13
 ******************************************************************************/

package org.pentaho.reporting.engine.classic.wizard.model;

import java.io.Serializable;

public interface WizardSpecification extends Cloneable, Serializable {
  public GroupDefinition[] getGroupDefinitions();

  public void setGroupDefinitions( final GroupDefinition[] groups );

  public DetailFieldDefinition[] getDetailFieldDefinitions();

  public void setDetailFieldDefinitions( final DetailFieldDefinition[] groups );

  public RootBandDefinition getColumnHeader();

  public RootBandDefinition getColumnFooter();

  public WatermarkDefinition getWatermarkDefinition();

  public Object clone() throws CloneNotSupportedException;

  public boolean isAutoGenerateDetails();

  public void setAutoGenerateDetails( final boolean autoGenerate );
}
