/*! ******************************************************************************
 *
 * Pentaho
 *
 * Copyright (C) 2024 by Hitachi Vantara, LLC : http://www.pentaho.com
 *
 * Use of this software is governed by the Business Source License included
 * in the LICENSE.TXT file.
 *
 * Change Date: 2028-08-13
 ******************************************************************************/

package org.pentaho.reporting.engine.classic.demo.ancient.demo.opensource;

import org.pentaho.reporting.engine.classic.core.ClassicEngineBoot;
import org.pentaho.reporting.engine.classic.core.MasterReport;
import org.pentaho.reporting.engine.classic.core.TableDataFactory;
import org.pentaho.reporting.engine.classic.core.modules.gui.base.PreviewApplet;

/**
 * This demo application replicates the report generated by OpenSourceXMLDemoHandler.java, but creates the report in
 * code rather than using an XML report template. The whole report is displayed in an applet.
 * <p/>
 * To use or adopt that applet to your own needs, just change the getReport() method and your applet should work
 * perfectly ...
 *
 * @author Thomas Morgner
 */
public class OpenSourceDemoApplet extends PreviewApplet
{
  /**
   * The report (created in code).
   */
  private MasterReport report;

  /**
   * Constructs the demo applet.
   */
  public OpenSourceDemoApplet()
  {
    // initialize JFreeReport
    ClassicEngineBoot.getInstance().start();
  }

  public void init()
  {
    super.init();
    setReportJob(createReport());
  }

  /**
   * Creates a report definition in code.
   * <p/>
   * It is more base to read the definition from an XML report template file, but sometimes you might need to create a
   * report dynamically.
   *
   * @return a report.
   */
  public MasterReport createReport()
  {

    if (this.report != null)
    {
      return this.report;
    }

    // uses the report from the OpenSourceXMLDemoHandler 2 ...
    this.report = OpenSourceAPIDemoHandler.createStaticReport();
    report.setDataFactory(new TableDataFactory("default", new OpenSourceProjects()));
    return report;
  }

}
