/*! ******************************************************************************
 *
 * Pentaho
 *
 * Copyright (C) 2024 by Hitachi Vantara, LLC : http://www.pentaho.com
 *
 * Use of this software is governed by the Business Source License included
 * in the LICENSE.TXT file.
 *
 * Change Date: 2028-08-13
 ******************************************************************************/

package org.pentaho.reporting.engine.classic.core.modules.parser.extwriter;

/**
 * An exception that can be generated by the
 * {@link org.pentaho.reporting.engine.classic.core.modules.parser .extwriter.ReportWriter} class.
 *
 * @author Thomas Morgner.
 */
public class ReportWriterException extends Exception {
  /**
   * Creates an exception with no message and no parent.
   */
  public ReportWriterException() {
  }

  /**
   * Creates an exception.
   *
   * @param message
   *          the exception message.
   * @param ex
   *          the parent exception.
   */
  public ReportWriterException( final String message, final Exception ex ) {
    super( message, ex );
  }

  /**
   * Creates an exception.
   *
   * @param message
   *          the exception message.
   */
  public ReportWriterException( final String message ) {
    super( message );
  }
}
