/* Generated By:JavaCC: Do not edit this line. GeneratedFormulaParserConstants.java */
package org.pentaho.reporting.libraries.formula.parser;

public interface GeneratedFormulaParserConstants {

  int EOF = 0;
  int WHITESPACE = 1;
  int LETTER = 3;
  int NON_ZERO_DIGIT = 4;
  int DIGIT = 5;
  int HEX_DIGIT = 6;
  int BINARY_DIGIT = 7;
  int UNSIGNED_INTEGER = 8;
  int EXPONENT_PART = 9;
  int NEWLINE = 10;
  int NONQUOTE_CHARACTER = 11;
  int NONQUOTE_LOOKUP = 12;
  int COMMA = 13;
  int PERIOD = 14;
  int COLON = 15;
  int QUOTE = 16;
  int DQUOTE = 17;
  int SEMICOLON = 18;
  int L_PAREN = 19;
  int R_PAREN = 20;
  int L_BRACKET = 21;
  int R_BRACKET = 22;
  int QUEST = 23;
  int L_BRACE = 24;
  int R_BRACE = 25;
  int PIPE = 26;
  int PLUS = 27;
  int MINUS = 28;
  int MULT = 29;
  int DIV = 30;
  int POW = 31;
  int EQUALS = 32;
  int NOT_EQUALS = 33;
  int LT_EQUALS = 34;
  int GT_EQUALS = 35;
  int LT = 36;
  int GT = 37;
  int CONCAT = 38;
  int PERCENT = 39;
  int IDENTIFIER = 40;
  int COLUMN_LOOKUP = 41;
  int STRING_LITERAL = 42;
  int UNSIGNED_NUMERIC_LITERAL = 43;
  int EXACT_NUMERIC_LITERAL = 44;
  int APPROXIMATE_NUMERIC_LITERAL = 45;
  int MANTISSA = 46;
  int SIGN = 47;
  int NULL = 48;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<token of kind 2>",
    "<LETTER>",
    "<NON_ZERO_DIGIT>",
    "<DIGIT>",
    "<HEX_DIGIT>",
    "<BINARY_DIGIT>",
    "<UNSIGNED_INTEGER>",
    "<EXPONENT_PART>",
    "<NEWLINE>",
    "<NONQUOTE_CHARACTER>",
    "<NONQUOTE_LOOKUP>",
    "\",\"",
    "\".\"",
    "\":\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"?\"",
    "\"{\"",
    "\"}\"",
    "\"|\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"=\"",
    "\"<>\"",
    "\"<=\"",
    "\">=\"",
    "\"<\"",
    "\">\"",
    "\"&\"",
    "\"%\"",
    "<IDENTIFIER>",
    "<COLUMN_LOOKUP>",
    "<STRING_LITERAL>",
    "<UNSIGNED_NUMERIC_LITERAL>",
    "<EXACT_NUMERIC_LITERAL>",
    "<APPROXIMATE_NUMERIC_LITERAL>",
    "<MANTISSA>",
    "<SIGN>",
    "\"null\"",
  };

}
