/*! ******************************************************************************
 *
 * Pentaho
 *
 * Copyright (C) 2024 by Hitachi Vantara, LLC : http://www.pentaho.com
 *
 * Use of this software is governed by the Business Source License included
 * in the LICENSE.TXT file.
 *
 * Change Date: 2029-07-20
 ******************************************************************************/


package org.pentaho.reporting.engine.classic.core.function;

/**
 * A structure function is a annonymous function that modifes the structure of the report or computes changes to the
 * report definition on the current report.
 * <p/>
 * Structure functions are considered to be part of the initial master-report. All events that were generated by
 * subreports are marked as deep-traversing events. The report-definition that is passed in the report-state is always
 * the report definition of the (sub) report that generated the event.
 *
 * @author Thomas Morgner
 */
public interface StructureFunction extends Function {
  public int getProcessingPriority();
}
